; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1CXVVM'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?CXCCM:NEAR

        PUBLIC          ?CXVVM                  ; Located at 1:0000h Type = 1

CODE    CSEG


?CXVVM: lodsb
        mov     cl,[di]
        inc     di
        jmp     ?CXCCM


        END

