; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1CXCVM'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?CXCCM:NEAR

        PUBLIC          ?CXCVM                  ; Located at 1:0000h Type = 1

CODE    CSEG


?CXCVM: mov     al,[di]
        inc     di
        xchg    al,cl
        jmp     ?CXCCM


        END

