; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FM44R'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?FM44:ABS
        EXTRN           ?S44MS:NEAR

        PUBLIC          ?FM44R                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FM44R: call    ?S44MS
        dw      ?FM44


        END

