; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FE40S'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?FE40M:NEAR

        PUBLIC          ?FE40S                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FE40S: pop     dx
        mov     bx,sp
        call    ?FE40M
        pop     bx
        pop     bx
        jmp     dx


        END

