; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FN40M'

        ; Compiler:     RASM-86 1.0 01/16/83



        PUBLIC          ?FN40M                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FN40M: pop     ax
        mov     dx,[bx]+002h
        xor     dh,80h
        push    dx
        push    word ptr [bx]
        jmp     ax


        END

