; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FPRET'

        ; Compiler:     RASM-86 1.0 01/16/83



        PUBLIC          ?FPRET                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FPRET: pop     dx
        pop     dx
        pop     cx
        pop     bx
        push    cx
        push    dx
        jmp     bx


        END

