; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FL40M'

        ; Compiler:     RASM-86 1.0 01/16/83



        PUBLIC          ?FL40M                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FL40M: pop     ax
        push    word ptr [bx]+002h
        push    word ptr [bx]
        ret


        END

