; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FM44M'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?FM44:ABS
        EXTRN           ?S44MM:NEAR

        PUBLIC          ?FM44M                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FM44M: call    ?S44MM
        dw      ?FM44


        END

