; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1FA44L'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?FA44:ABS
        EXTRN           ?S44SM:NEAR

        PUBLIC          ?FA44L                  ; Located at 1:0000h Type = 1

CODE    CSEG


?FA44L: call    ?S44SM
        dw      ?FA44


        END

