; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1IE10N'

        ; Compiler:     RASM-86 1.0 01/16/83



        PUBLIC          ?IE10N                  ; Located at 1:0000h Type = 1

CODE    CSEG


?IE10N: cbw
        or      al,ah
        jz      @j1
        js      @j1
        mov     al,01h
@j1:    ret


        END

