; OBJASM version 2.0 released on Jan 3, 1991
; (C) Copyright 1988,1989,1990,1991 by Robert F. Day.  All rights reserved

        TITLE   'PL1SCVCM'

        ; Compiler:     RASM-86 1.0 01/16/83


        EXTRN           ?SCCCM:NEAR

        PUBLIC          ?SCVCM                  ; Located at 1:0000h Type = 1

CODE    CSEG


?SCVCM: mov     cl,[si]
        inc     si
        jmp     ?SCCCM


        END

